
oslo.nt: OSLO-build
	find OSLO-build/ns/ -name *.nt -exec cat {} \; > oslo.nt
OSLO-build:
	mkdir OSLO-build
	git clone https://github.com/Informatievlaanderen/data.vlaanderen.be-generated.git -b production OSLO-build/

